[versions]
releaseVersion = "1.11.0"
compileSdkVersion = "36"
minSdkVersion = "23"
libTestTargetSdkVersion = "36"
androidxTestOrchestratorVersion = "1.6.1"
androidxTestCoreVersion = "1.5.0"
androidxTestEspressoVersion = "3.5.1"
androidxTestJUnitVersion = "1.1.5"
androidxTestRunnerVersion = "1.6.2"
androidxTestTruthVersion = "1.5.0"
androidxExifInterfaceVersion = "1.3.6"
dexmakerVersion = "2.28.3"
kotlinxCoroutinesVersion = "1.9.0"
androidxConcurrentFuturesVersion = "1.2.0"
guavaVersion = "33.3.1-android"
runnerVersion = "1.7.0"
animalSnifferAnnotationsVersion = "1.21"
junitVersion = "4.13.2"
mockitoVersion = "3.12.4"
mockitoMpvplayerVersion = "5.23.0"
androidxTestUiAutomatorVersion = "2.3.0"
androidxWindowVersion = "1.3.0"
androidxRecyclerViewVersion = "1.3.0"
robolectricVersion = "4.16"
testParameterInjectorVersion = "1.22"
truthVersion = "1.4.0"
agp = "9.3.1"
python = "17.0.0"
minSdk = "24"
targetSdk = "37"
compileSdk = "37"

annotation = "1.10.0"
exifinterface = "1.3.7"
annotationExperimental = "1.4.1"
errorprone = "2.28.0"
checkerframework = "3.42.0"
kotlinAnnotations = "2.0.20"
j2objcAnnotations = "3.0.0"
animalSniffer = "1.23"
jsr305 = "3.0.2"
appcompat = "1.7.1"
biometric = "1.1.0"
desugar = "2.1.5"
leanback = "1.2.0"
lifecycleService = "2.11.0"
media = "1.8.0"
palette = "1.0.0"
preference = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.4"
splashscreen = "1.2.0"
startup = "1.2.0"
swiperefreshlayout = "1.2.0"
viewpager2 = "1.1.0"

androidGifDrawable = "1.2.32"
androidautosize = "1.2.1"
brotli = "0.1.2"
customactivityoncrash = "2.4.0"
flexbox = "3.0.0"
glide = "5.0.9"
greenrobot = "3.3.1"
gson = "2.14.0"
guava = "33.6.0-android"
jna = "5.19.1"
jupnp = "3.0.4"
juniversalchardet = "1.0.3"
logger = "2.2.0"
lottie = "6.7.1"
material = "1.14.0"
materialdesigncolors = "1.0.0"
nanohttpd = "2.3.1"
newpipeextractor = "v0.26.4"
okhttp = "5.4.0"
permissionx = "1.8.1"
quickjs = "3.2.3"
rtmpClient = "v3.2.0.m2"
sardine = "0.9"
simpleXml = "2.7.1"
smbj = "0.14.0"
textdrawable = "1.0.3"
zxingAndroidEmbedded = "4.3.0"
zxingCore = "3.5.4"

[libraries]
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidxTestOrchestratorVersion" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "androidxExifInterfaceVersion" }
dexmaker-mockito = { group = "com.linkedin.dexmaker", name = "dexmaker-mockito", version.ref = "dexmakerVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.9.0" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesVersion" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "androidxConcurrentFuturesVersion" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runnerVersion" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesVersion" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesVersion" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }
brotli-dec = { group = "org.brotli", name = "dec", version.ref = "brotli" }
androidx-annotation-experimental = { group = "androidx.annotation", name = "annotation-experimental", version.ref = "annotationExperimental" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCoreVersion" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJUnitVersion" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunnerVersion" }
androidx-test-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidxTestTruthVersion" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspressoVersion" }
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockito-mpvplayer = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoMpvplayerVersion" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestUiAutomatorVersion" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindowVersion" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerViewVersion" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectricVersion" }
test-parameter-injector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testParameterInjectorVersion" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truthVersion" }
guava-testlib = { group = "com.google.guava", name = "guava-testlib", version.ref = "guava" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
annotation-experimental = { group = "androidx.annotation", name = "annotation-experimental", version.ref = "annotationExperimental" }
exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
errorprone-annotations = { group = "com.google.errorprone", name = "error_prone_annotations", version.ref = "errorprone" }
checkerframework-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
kotlin-annotations-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-annotations-jvm", version.ref = "kotlinAnnotations" }
j2objc-annotations = { group = "com.google.j2objc", name = "j2objc-annotations", version.ref = "j2objcAnnotations" }
animal-sniffer-annotations = { group = "org.codehaus.mojo", name = "animal-sniffer-annotations", version.ref = "animalSniffer" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }
leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

android-gif-drawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "androidGifDrawable" }
androidautosize = { group = "com.github.JessYanCoding", name = "AndroidAutoSize", version.ref = "androidautosize" }
brotli = { group = "org.brotli", name = "dec", version.ref = "brotli" }
customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "customactivityoncrash" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "greenrobot" }
eventbus-annotation-processor = { group = "org.greenrobot", name = "eventbus-annotation-processor", version.ref = "greenrobot" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "glide" }
glide-avif-integration = { group = "com.github.bumptech.glide", name = "avif-integration", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
juniversalchardet = { group = "com.googlecode.juniversalchardet", name = "juniversalchardet", version.ref = "juniversalchardet" }
rtmp-client = { group = "com.github.mcxinyu", name = "LibRtmp-Client-for-Android", version.ref = "rtmpClient" }
logger = { group = "com.orhanobut", name = "logger", version.ref = "logger" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
materialdesigncolors = { group = "com.github.bassaer", name = "materialdesigncolors", version.ref = "materialdesigncolors" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
newpipeextractor = { group = "com.github.TeamNewPipe", name = "NewPipeExtractor", version.ref = "newpipeextractor" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
org-jupnp = { group = "org.jupnp", name = "org.jupnp", version.ref = "jupnp" }
org-jupnp-android = { group = "org.jupnp", name = "org.jupnp.android", version.ref = "jupnp" }
org-jupnp-support = { group = "org.jupnp", name = "org.jupnp.support", version.ref = "jupnp" }
permissionx = { group = "com.guolindev.permissionx", name = "permissionx", version.ref = "permissionx" }
quickjs-android = { group = "wang.harlon.quickjs", name = "wrapper-android", version.ref = "quickjs" }
quickjs-java = { group = "wang.harlon.quickjs", name = "wrapper-java", version.ref = "quickjs" }
sardine = { group = "com.github.thegrizzlylabs", name = "sardine-android", version.ref = "sardine" }
simple-xml = { group = "org.simpleframework", name = "simple-xml", version.ref = "simpleXml" }
smbj = { group = "com.hierynomus", name = "smbj", version.ref = "smbj" }
textdrawable = { group = "com.github.jahirfiquitiva", name = "TextDrawable", version.ref = "textdrawable" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
chaquo-python = { id = "com.chaquo.python", version.ref = "python" }

[bundles]
glide = ["glide", "glide-annotations", "glide-avif-integration", "glide-okhttp3-integration"]
jupnp = ["org-jupnp", "org-jupnp-android", "org-jupnp-support"]
okhttp = ["okhttp", "okhttp-dnsoverhttps", "okhttp-logging-interceptor"]
